/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as helpers from "./helpers";
export type { helpers };
import type * as mocks from "./mocks";
export type { mocks };
import type * as templates from "./templates";
export type { templates };
export type { SimpleStorage } from "./SimpleStorage";
