/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface OracleGasOptimizedInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getLatestValue"
      | "isReporter"
      | "updateReporter"
      | "updateValue"
      | "updateValueWithProof"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ReporterUpdate" | "ValueUpdate"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getLatestValue",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isReporter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateReporter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateValue",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateValueWithProof",
    values: [BytesLike, BytesLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getLatestValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isReporter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateReporter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateValueWithProof",
    data: BytesLike
  ): Result;
}

export namespace ReporterUpdateEvent {
  export type InputTuple = [newUpdater: AddressLike];
  export type OutputTuple = [newUpdater: string];
  export interface OutputObject {
    newUpdater: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValueUpdateEvent {
  export type InputTuple = [
    id: BytesLike,
    value: BigNumberish,
    updatedAt: BigNumberish
  ];
  export type OutputTuple = [id: string, value: bigint, updatedAt: bigint];
  export interface OutputObject {
    id: string;
    value: bigint;
    updatedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OracleGasOptimized extends BaseContract {
  connect(runner?: ContractRunner | null): OracleGasOptimized;
  waitForDeployment(): Promise<this>;

  interface: OracleGasOptimizedInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getLatestValue: TypedContractMethod<
    [id: BytesLike],
    [[bigint, bigint] & { value: bigint; updatedAt: bigint }],
    "view"
  >;

  isReporter: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  updateReporter: TypedContractMethod<
    [newReporter: AddressLike],
    [void],
    "nonpayable"
  >;

  updateValue: TypedContractMethod<
    [id: BytesLike, value: BigNumberish, timestamp: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateValueWithProof: TypedContractMethod<
    [message: BytesLike, extraData: BytesLike, signedFor: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getLatestValue"
  ): TypedContractMethod<
    [id: BytesLike],
    [[bigint, bigint] & { value: bigint; updatedAt: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "isReporter"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "updateReporter"
  ): TypedContractMethod<[newReporter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateValue"
  ): TypedContractMethod<
    [id: BytesLike, value: BigNumberish, timestamp: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateValueWithProof"
  ): TypedContractMethod<
    [message: BytesLike, extraData: BytesLike, signedFor: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ReporterUpdate"
  ): TypedContractEvent<
    ReporterUpdateEvent.InputTuple,
    ReporterUpdateEvent.OutputTuple,
    ReporterUpdateEvent.OutputObject
  >;
  getEvent(
    key: "ValueUpdate"
  ): TypedContractEvent<
    ValueUpdateEvent.InputTuple,
    ValueUpdateEvent.OutputTuple,
    ValueUpdateEvent.OutputObject
  >;

  filters: {
    "ReporterUpdate(address)": TypedContractEvent<
      ReporterUpdateEvent.InputTuple,
      ReporterUpdateEvent.OutputTuple,
      ReporterUpdateEvent.OutputObject
    >;
    ReporterUpdate: TypedContractEvent<
      ReporterUpdateEvent.InputTuple,
      ReporterUpdateEvent.OutputTuple,
      ReporterUpdateEvent.OutputObject
    >;

    "ValueUpdate(bytes32,uint128,uint128)": TypedContractEvent<
      ValueUpdateEvent.InputTuple,
      ValueUpdateEvent.OutputTuple,
      ValueUpdateEvent.OutputObject
    >;
    ValueUpdate: TypedContractEvent<
      ValueUpdateEvent.InputTuple,
      ValueUpdateEvent.OutputTuple,
      ValueUpdateEvent.OutputObject
    >;
  };
}
