/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IToken } from "./IToken";
export type { IX2EarnAppsMock } from "./IX2EarnAppsMock";
export type { IX2EarnRewardsPool } from "./IX2EarnRewardsPool";
export type { IXAllocationVotingGovernor } from "./IXAllocationVotingGovernor";
