/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as oracle from "./oracle";
export type { oracle };
export type { B3TR_Mock } from "./B3TR_Mock";
export type { MyERC1155 } from "./MyERC1155";
export type { MyERC721 } from "./MyERC721";
export type { X2EarnAppsMock } from "./X2EarnAppsMock";
export type { X2EarnRewardsPoolMock } from "./X2EarnRewardsPoolMock";
export type { XAllocationVotingGovernorMock } from "./XAllocationVotingGovernorMock";
